default: &default
  adapter: postgresql
  encoding: UTF-8
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  database: repos
  host: localhost
  username: pgadmin
  password: teo123

test:
  <<: *default
  database: repos_test
  host: localhost
  username: pgadmin
  password: teo123

production:
  <<: *default
  database: repos
  #username: zucattodoc
  #password: <%= ENV['ZUCATTODOC_DATABASE_PASSWORD'] %>
  host: ec2-54-163-229-169.compute-1.amazonaws.com
  username: uinxlqtbdxoctn
  password: 2be43004b3ce1d77e4b3a7b6cfc63c061b2532278cce5af406293fa312d0e453
  port: 5432
  